// flow-typed signature: 99cf4a67e8abd6962ed699fcf7581149
// flow-typed version: <<STUB>>/lodash-uuid_v0.0.3/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash-uuid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash-uuid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lodash-uuid/test/isUuid.spec' {
  declare module.exports: any;
}

declare module 'lodash-uuid/test/isUuid4.spec' {
  declare module.exports: any;
}

declare module 'lodash-uuid/test/uuid.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lodash-uuid/index' {
  declare module.exports: $Exports<'lodash-uuid'>;
}
declare module 'lodash-uuid/index.js' {
  declare module.exports: $Exports<'lodash-uuid'>;
}
declare module 'lodash-uuid/test/isUuid.spec.js' {
  declare module.exports: $Exports<'lodash-uuid/test/isUuid.spec'>;
}
declare module 'lodash-uuid/test/isUuid4.spec.js' {
  declare module.exports: $Exports<'lodash-uuid/test/isUuid4.spec'>;
}
declare module 'lodash-uuid/test/uuid.spec.js' {
  declare module.exports: $Exports<'lodash-uuid/test/uuid.spec'>;
}
