// flow-typed signature: bcf8d7f8b5f2328a87309102658bbf4a
// flow-typed version: <<STUB>>/react-move/Animate_v2.7.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-move/Animate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-move/Animate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-move/Animate/Animate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-move/Animate/Animate.js' {
  declare module.exports: $Exports<'react-move/Animate/Animate'>;
}
declare module 'react-move/Animate/index' {
  declare module.exports: $Exports<'react-move/Animate'>;
}
declare module 'react-move/Animate/index.js' {
  declare module.exports: $Exports<'react-move/Animate'>;
}
